### ISSUE TITLE
Document what registerNotificationChannel returns?

### ISSUE THREAD

**Issue by safield** [caseyryan/flutter_notification_channel#2]
What does the string represent that is returned from registerNotificationChannel call?

**Comment by caseyryan** [comment]
It simply returns a message of a registration status. It can be a message of successful channel registration or an error. Just for debugging purposes

**Comment by safield** [comment]
It should be an enum or a class then, not a string.

**Comment by caseyryan** [comment]
I needed a string

**Comment by safield** [comment]
You are doing it wrong.

**Comment by caseyryan** [comment]
This plugin was written for one of my old projects a few years ago. Mostly as a quick solution to a problem. It solved that problem 100%. Then I decided to publish it. I agree it would be more correct to return some uniform type like enum or an int or even a string constant. But I don't need it and I don't have time for it, sorry. If you want it to return an enum, please, feel free to make a pull request with your solution
