### ISSUE TITLE
Add support for custom sounds

### ISSUE THREAD

**Issue by cgfischer** [caseyryan/flutter_notification_channel#3]
I'm looking for an easy way to configure a new Notification Channel with a custom sound file (e.g. *.wav file).

I think it would be valuable to support a method for specifying a "customSound" property (in addition to "enableSound").  The customSound would be String representing the name of a file to be used instead of the system notification sound (Settings.System.DEFAULT_NOTIFICATION_URI).  The "customSound" would be passed as a string and be resolved through the application res/raw resources.  Maybe something like:

uri = Uri.parse(ContentResolver.SCHEME_ANDROID_RESOURCE + "://"+ getApplicationContext().getPackageName() + "/raw/<customSound>");

**Comment by caseyryan** [comment]
It sounds like a reasonable solution but unfortunately I don't have time to support my old projects at all. If you really need this functionality, please, feel free to make a pull request with that

**Comment by cgfischer** [comment]
I sent a pull request.  Do you have any feedback?

**Comment by caseyryan** [comment]
Added here https://pub.dev/packages/flutter_notification_channel
