### ISSUE TITLE
Upgrade plugin to latest flutter standards

### ISSUE THREAD

**Issue by jtmcdole** [caseyryan/flutter_notification_channel#6]
assign:me

**Comment by PiotrWpl** [comment]
Hi @caseyryan 

great package. Can I ask you when you are planning to release those changes on pub.dev? Because I got a compilation error when I tried to add the latest app version from there, but I succeeded with the version I got directly from Github.

**Comment by caseyryan** [comment]
> Hi @caseyryan
> 
> great package. Can I ask you when you are planning to release those changes on pub.dev? Because I got a compilation error when I tried to add the latest app version from there, but I succeeded with the version I got directly from Github.

Hi. I must have forgotten about it. Just merged and published https://pub.dev/packages/flutter_notification_channel version 3.1.0.
